const techMedia = [
  { type: "video", src: "videos/looking_glass.mp4", poster: "images/tech/looking_glass_thumb.jpg" },
  "images/tech/smartorowatch1.jpg",
  "images/tech/smartorowatch2.jpg",
  "images/tech/smartorowatch3.jpg",
  "images/tech/battery.jpg",
  "images/tech/battery_gokugoku.jpg",
  "images/tech/bg_center.jpg",
  "images/tech/live02.png",
  "images/tech/live03.jpg",
  "images/tech/osakanya.jpg",
  "images/tech/proto1.png",
  "images/tech/proto2.png",
  "images/tech/super_toroid.jpg",
  "images/tech/toro_wallpaper.png",
  
];

const illustMedia = [
  "images/illust/halloween2016.jpg",
  "images/illust/halloween2018.png",
  "images/illust/halloween2017.jpg",
  "images/illust/halloween2015.png",
  "images/illust/halloween2014.png",
  "images/illust/halloween2013.png",
  "images/illust/halloween2012.png",
  "images/illust/halloween2011.png",
  "images/illust/halloween2010.png",
  "images/illust/halloween.png",
  "images/illust/kyuukei.jpg",
  "images/illust/dakimakura_cover.jpg",
  "images/illust/rengoku.jpg",
  "images/illust/nengazyo2017.jpg",
  "images/illust/nengazyo2020.jpg",
  "images/illust/nengazyo2019.png",
  "images/illust/nengazyo2018.jpg",
  "images/illust/nengazyo2025.jpg",
  "images/illust/nengazyo2013_2.png",
  "images/illust/nengazyo2012.png",
  "images/illust/nengazyo2011.png",
  "images/illust/18th.jpg",
  "images/illust/20th.jpg",
  "images/illust/19th.png",
  "images/illust/21th.jpg",
  "images/illust/23th.jpg",
  "images/illust/17th.jpg",
  "images/illust/16th.png",
  "images/illust/15th.jpg",
  "images/illust/torona.png",
  "images/illust/xmas2017.jpg",
  "images/illust/xmas2013.png",
  "images/illust/xmas2012.png",
  "images/illust/alisa.png",
  "images/illust/birthday.png",
  "images/illust/coat.png",
  "images/illust/twitter.png",
  "images/illust/mikutoro2011.png",
  "images/illust/mikutoro2010.png",
  "images/illust/kotowaru.png",
];

const plushMedia = [
  "images/plush/hiyoko.jpg",
  "images/plush/akuma.jpg",
  "images/plush/kekkon.jpg",
  "images/plush/king.jpg",
  "images/plush/koteki.jpg",
  "images/plush/maid.jpg",
  "images/plush/ohana.jpg",
  "images/plush/ninja.jpg",
  "images/plush/ninja2.jpg",
  "images/plush/madoka.jpg",
  "images/plush/airu.jpg",
  "images/plush/hime.jpg",
  "images/plush/yopparai.jpg",
];

const foodMedia = [
  "images/food/toroman01.jpg",
  "images/food/toroman02.jpg",
  "images/food/toroman03.jpg",
  "images/food/tokkuri.jpg",
  "images/food/cake.jpg",
  "images/food/choko01.jpg",
  "images/food/cookie.jpg",
  "images/food/okonomi.jpg",
  "images/food/omu02.jpg",
  "images/food/potato.jpg",
  "images/food/toroben.jpg",
];

const photoMedia = [
  "images/photo/torodaruma2012.jpg",
  "images/photo/santa.jpg",
];

const mediaLists = {
  tech: techMedia,
  illust: illustMedia,
  plush: plushMedia,
  food: foodMedia,
  photo: photoMedia,
};
